version: "3"
services:
  bossabox-db:
    image: postgres
    container_name: bossabox-db
    environment:
      POSTGRES_PASSWORD: bossabox
      POSTGRES_USER: bossabox
      POSTGRES_DB: vuttr
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
    ports:
      - 5432:5432
    networks: 
      - bossabox-network
          
  bossabox-backend:
    build: .
    container_name: bossabox-backend
    volumes:
      - .:/usr/app
    ports:
      - "3000:3000"
    depends_on: 
      - bossabox-db
    networks: 
      - bossabox-network

networks: 
  bossabox-network:
    driver: bridge
